# Jwt configuration for {JwtFactory.class}
jwt:
  secret: somesecret
  issuer: http://localhost:8080
# Database configuration with h2. Just for testing purpose. Uses auto generation of sql.
database:
  driverClass: org.h2.Driver
  url: jdbc:h2:file:./test-database
  user: sa
  password:
  properties:
          hibernate.dialect: org.hibernate.dialect.H2Dialect
          hibernate.hbm2ddl.auto: update